# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9c411f3eaeab934bc390c9918062f3459195ecd12282e291d3c7577d9fd2880732468ef2654ab7cdc7188c6c4607ede1881a626c7c6d358de13effd2864891a

test:
  secret_key_base: 59e29330106098f5e4f8723505362db54aadb72a27bd06c355c9edacd457c596eb323ee1ef2bb75747baa85acb6cbb2807e4ffdff9dbcbef90b50edcba8a65ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
